" Global vim options
syntax on
set nu hls ruler modeline
set tabstop=2 shiftwidth=2 softtabstop=2 expandtab

" Global custom highlighting rules
highlight OverLength ctermbg=red ctermfg=white

" Highlight if line length exceeds 80 chars (this gets annoying really fast)
"match OverLength /\%>80v.\+/

" Python-specific
" See PEP 8 (Style Guide) at http://www.python.org/dev/peps/pep-0008/
au FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4
au FileType python match OverLength /\%>79v.\+/
