" Global vim options
syntax on
filetype indent plugin on
set nocompatible
set nonu hls ruler modeline
set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab autoindent
set modelines=99999 " Override OS X default of no modelines

" Global custom highlighting rules
highlight OverLength ctermbg=red ctermfg=white

" Highlight if line length exceeds 80 chars (this gets annoying really fast)
"match OverLength /\%>80v.\+/

" Python-specific
" See PEP 8 (Style Guide) at http://www.python.org/dev/peps/pep-0008/
au FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4
au FileType python match OverLength /\%>79v.\+/

" Ruby-specific
au FileType ruby setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
au FileType ruby match OverLength /\%>79v.\+/

" Fix Markdown filetype detection
au BufRead,BufNewFile *.md set filetype=markdown

" vim-signify options
highlight SignColumn                       ctermbg=none
highlight DiffAdd               cterm=bold ctermbg=none ctermfg=2
highlight DiffDelete            cterm=bold ctermbg=none ctermfg=1
highlight DiffChange            cterm=bold ctermbg=none ctermfg=3
highlight SignifySignAdd        cterm=bold ctermbg=none  ctermfg=2
highlight SignifySignDelete     cterm=bold ctermbg=none  ctermfg=1
highlight SignifySignChange     cterm=bold ctermbg=none  ctermfg=3
